### ISSUE TITLE
Issue with boolean type

### ISSUE THREAD

**Issue by vlad88sv** [jordillonch/CrudGeneratorBundle#34]
Hi!, very nice bundle!, thank you!.

I've spotted an issue with boolean data type, in which you can save a form if the field is "nullable: false".

I was expecting it to store 0 when checkbox is empty and 1 when it's checked, but it seems it defaults to null & 1, and when the field is not nullable then you can't save the form without checking the field.

Also, would be a nice feature if it showed a "checked" icon on the index/list action for boolean fields just like Symfony1's admin generator did :+1: 

I'm using Symfony 2.3.23 & CrudGeneratorBundle 2.3.x-dev

**Comment by jordillonch** [comment]
I'm sorry but I don't have time to verify and fix that. It would be nice if you could provide a pull request solving it.

**Comment by l-vo** [comment]
@jordillonch: I think #46 closes this issue.
