### ISSUE TITLE
Symfony 2.7 & Doctrine orm 2.5 ... we need the update!

### ISSUE THREAD

**Issue by SherifMedhat** [jordillonch/CrudGeneratorBundle#36]
Why you are restricting dependencies to:
 "symfony/symfony": ">2.2.0, <2.7-dev",
 "doctrine/orm": ">=2.2.3,<2.5-dev"
?

**Comment by sjert** [comment]
Yes, this is also preventing me from upgrading to Symfony 2.7!

**Comment by jordillonch** [comment]
Ok, the restriction is removed
