### ISSUE TITLE
Symfony 2.7.2 Error

### ISSUE THREAD

**Issue by icemouton** [jordillonch/CrudGeneratorBundle#38]
There is an error in JordiLlonchCrudCommand.php [61] 
Where $this->getDialogHelper() is, it is no longer a part of the Sensio Generator Bundle and should be replaced with
 $dialog = $this->getQuestionHelper();

Just thought I would let you know.

**Comment by nilopc** [comment]
Why not a PR @icemouton ? :)

**Comment by jordillonch** [comment]
@dyktek fixed it :)
