### ISSUE TITLE
Issue in Symfony 2.8

### ISSUE THREAD

**Issue by allo86** [jordillonch/CrudGeneratorBundle#41]
I am getting this error when trying to create the CRUD:

[Symfony\Component\Debug\Exception\ContextErrorException]                    
  Warning: Missing argument 2 for Sensio\Bundle\GeneratorBundle\Generator\Doc  
  trineCrudGenerator::__construct(), called in /var/www/html/pruebas/vendor/j  
  ordillonch/crud-generator/JordiLlonch/Bundle/CrudGeneratorBundle/Command/Jo  
  rdiLlonchCrudCommand.php on line 38 and defined

**Comment by jordillonch** [comment]
I'm sorry but I don't have time to look the issue. Please try to find the problem and open a pull request if there is a problem in the bundle.

**Comment by lcube45** [comment]
JordiLlonchCrudCommand is extending GenerateDoctrineCrudCommand which is waiting for 2 parameters in is constructor :
- filesystem
- rootdir

Changes made on SensioGeneratorBundle on the 05/12/2015 in the master branch

**Comment by jordillonch** [comment]
Great! Please create a pull request.

**Comment by lcube45** [comment]
i'll try

**Comment by hatabdel** [comment]
I have the same problem,, please any solution !!!

**Comment by lcube45** [comment]
patch file : jordillonch\crud-generator\JordiLlonch\Bundle\CrudGeneratorBundle\Command\JordiLlonchCrudCommand.php line 38 as following

`    protected function createGenerator($bundle = null)
    {
        return new JordiLlonchCrudGenerator($this->getContainer()->get('filesystem'),$this->getContainer()->get('kernel')->getRootDir());
    }`

**Comment by gonzakpo** [comment]
Buenas hice algunos cambios en mi version de Crud pero aun no funciona del todo bien igual les paso el repo para ver si nos ayuda a todos:  https://github.com/MWSimple/AdminCrudBundle/blob/version30/Command/MWSimpleCrudCommand.php

**Comment by jordillonch** [comment]
Fixed

**Comment by jordillonch** [comment]
Thanks @lcube45 for the patch suggestion.
