### ISSUE TITLE
Missing argument 2 for Sensio\Bundle\GeneratorBundle\Generator\Doc  trineCrudGenerator::__construct()

### ISSUE THREAD

**Issue by hatabdel** [jordillonch/CrudGeneratorBundle#43]
I am getting this error when trying to create the CRUD:

[Symfony\Component\Debug\Exception\ContextErrorException]

Warning: Missing argument 2 for Sensio\Bundle\GeneratorBundle\Generator\Doc

trineCrudGenerator::__construct(), called in /var/www/html/pruebas/vendor/j

ordillonch/crud-generator/JordiLlonch/Bundle/CrudGeneratorBundle/Command/Jo

rdiLlonchCrudCommand.php on line 38 and defined

**Comment by jordillonch** [comment]
Fixed

**Comment by hatabdel** [comment]
OK
