### ISSUE TITLE
CrudGenerator in Symfony 3

### ISSUE THREAD

**Issue by dkachuk** [jordillonch/CrudGeneratorBundle#44]
Hello!
The bundle does not work on symfony 3. What can be done to correct this situation?
Thanks!!!

**Comment by jordillonch** [comment]
Well, I've not planned to update the bundle to sf3 for the moment but if you do and create a pull request it will be great.

**Comment by dkachuk** [comment]
Hello! =)
Thanks for the reply! Successes !!!
